repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - "--indent=2"
          - "--autofix"
      - id: check-json
      - id: check-yaml
        exclude: ^\.github/
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/crate-ci/typos
    rev: v1.48.0
    hooks:
      - id: typos

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.31
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-check
        args: [--fix, --unsafe-fixes]
      - id: ruff-format

  - repo: https://github.com/pycqa/flake8
    rev: "7.3.0"
    hooks:
      - id: flake8
        additional_dependencies:
          - wemake-python-styleguide==1.6.2
        files: ^fogws/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml, --install-types, --non-interactive]
        files: ^(fogws|tests)/.*\.pyi?$
