from collections.abc import Awaitable

__version__: str

DEFAULT_CLOSE_TIMEOUT: float
DEFAULT_MAX_BUFFERED_BYTES: int
DEFAULT_MAX_MESSAGE_SIZE: int
DEFAULT_MAX_QUEUE: int

class FogWSError(Exception): ...

class ConnectionClosed(FogWSError):
    code: int | None
    reason: str
    initiated_by_local: bool | None

class ConnectionClosedError(ConnectionClosed): ...
class ConnectionClosedOK(ConnectionClosed): ...
class ConcurrencyError(FogWSError): ...
class ConnectionFailedError(FogWSError): ...
class InvalidURIError(FogWSError): ...
class LoopAffinityError(FogWSError): ...
class ResourceLimitError(FogWSError): ...
class RuntimeContextError(FogWSError): ...

class _Connection:
    def _abort(self, pending_receive: object | None) -> None: ...
    def _ensure_context(self) -> None: ...
    def send_text(self, payload: str) -> Awaitable[None]: ...
    def send_bytes(self, payload: bytes) -> Awaitable[None]: ...
    def receive(self) -> Awaitable[str | bytes]: ...
    def close(self) -> Awaitable[None]: ...

def _connect(
    uri: str,
    *,
    max_queue: int = ...,
    max_message_size: int = ...,
    max_buffered_bytes: int = ...,
    close_timeout: float = ...,
) -> Awaitable[_Connection]: ...
